services:
  - type: web
    name: nicapharmtechnologie
    env: node
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
