services:
  - type: web
    name: nicapharmtechnologie
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
