# Generated by Django 5.2.1 on 2025-08-15 20:57

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('pays_origine', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicitePharmacie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='publicites/')),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Format: 8-15 chiffres sans espaces/caractères', regex='^[0-9]{8,15}$')])),
                ('score_fidelite', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dernier_achat', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_depense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='comptes.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(default='en_attente', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.pharmacie')),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categorie', models.CharField(choices=[('transport', 'Transport'), ('nourriture', 'Nourriture'), ('achat_materiel', 'Achat de matériel'), ('salaire', 'Salaire'), ('Loyer', 'Loyer'), ('Autre', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode_paiement', models.CharField(choices=[('cash', 'Cash')], default='cash', max_length=50)),
                ('date_depense', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='comptes.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='DepotPharmaceutique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_depot', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('adresse_complete', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='pharmacie.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tension_arterielle', models.CharField(blank=True, max_length=10, null=True)),
                ('examen_malaria', models.BooleanField(default=False)),
                ('date_exam', models.DateTimeField(auto_now_add=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitFabricant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(db_index=True, max_length=255)),
                ('prix_achat', models.DecimalField(decimal_places=5, max_digits=10)),
                ('devise', models.CharField(choices=[('USD', 'Dollar américain'), ('CDF', 'Franc congolais')], default='CDF', max_length=3)),
                ('nombre_plaquettes_par_boite', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='pharmacie.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduitLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_commandee', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.commandeproduit')),
                ('produit_fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitfabricant')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPharmacie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_barre', models.CharField(max_length=100, unique=True)),
                ('nom_medicament', models.CharField(max_length=255)),
                ('indication', models.TextField(blank=True, null=True)),
                ('localisation', models.CharField(max_length=255)),
                ('conditionnement', models.CharField(choices=[('pièce', 'Pièce'), ('boîte', 'Boîte'), ('carton', 'Carton')], max_length=20)),
                ('date_peremption', models.DateField()),
                ('categorie', models.CharField(max_length=100)),
                ('alerte_quantite', models.PositiveIntegerField()),
                ('quantite', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marge_beneficiaire', models.DecimalField(decimal_places=2, help_text='En pourcentage', max_digits=5)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_pharmacie', to='comptes.pharmacie')),
                ('produit_fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitfabricant')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=50)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('duree_traitement', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.client')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitpharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='LotProduitPharmacie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lot', models.CharField(blank=True, help_text='Numéro du lot (fourni par le fournisseur ou généré automatiquement)', max_length=100, null=True, unique=True)),
                ('date_peremption', models.DateField()),
                ('date_entree', models.DateField(auto_now_add=True)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacie.produitpharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField()),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('points_gagnes', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitpharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='pharmacie.commandeproduit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_recue', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.commandeproduitligne')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.receptionproduit')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heure', models.TimeField(default=datetime.time(9, 0))),
                ('statut', models.CharField(choices=[('à venir', 'à venir'), ('passé', 'passé')], default='à venir', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.client')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_personnalise', models.CharField(blank=True, max_length=100)),
                ('nombre_demandes', models.PositiveIntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.pharmacie')),
                ('produit_fabricant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.produitfabricant')),
            ],
        ),
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='pharmacie.client')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='comptes.pharmacie')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenteLigne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitpharmacie')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.venteproduit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('pharmacie', 'telephone'), name='unique_phone_per_pharmacy'),
        ),
    ]
