# Generated by Django 5.2.1 on 2025-06-03 06:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('pays_origine', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Format: 8-15 chiffres sans espaces/caractères', regex='^[0-9]{8,15}$')])),
                ('score_fidelite', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dernier_achat', models.DateTimeField(blank=True, null=True)),
                ('total_depense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='comptes.pharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(default='en_attente', max_length=50)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.pharmacie')),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_arterielle', models.CharField(blank=True, max_length=10, null=True)),
                ('examen_malaria', models.BooleanField(default=False)),
                ('date_exam', models.DateTimeField(auto_now_add=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitFabricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(choices=[('USD', 'Dollar américain'), ('CDF', 'Franc congolais')], default='CDF', max_length=3)),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='pharmacie.fabricant')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduitLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commandee', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.commandeproduit')),
                ('produit_fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitfabricant')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barre', models.CharField(max_length=100, unique=True)),
                ('nom_medicament', models.CharField(max_length=255)),
                ('indication', models.TextField(blank=True, null=True)),
                ('localisation', models.CharField(max_length=255)),
                ('conditionnement', models.CharField(choices=[('pièce', 'Pièce'), ('boîte', 'Boîte'), ('carton', 'Carton')], max_length=20)),
                ('date_peremption', models.DateField()),
                ('categorie', models.CharField(max_length=100)),
                ('alerte_quantite', models.PositiveIntegerField()),
                ('quantite', models.PositiveIntegerField()),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marge_beneficiaire', models.DecimalField(decimal_places=2, help_text='En pourcentage', max_digits=5)),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_pharmacie', to='comptes.pharmacie')),
                ('produit_fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitfabricant')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('duree_traitement', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.client')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitpharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('points_gagnes', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitpharmacie')),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='pharmacie.commandeproduit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_recue', models.PositiveIntegerField()),
                ('ligne_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.commandeproduitligne')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.receptionproduit')),
            ],
        ),
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes', to='pharmacie.client')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='comptes.pharmacie')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenteLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.produitpharmacie')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='pharmacie.venteproduit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('pharmacie', 'telephone'), name='unique_phone_per_pharmacy'),
        ),
    ]
