# Generated by Django 5.2.1 on 2025-08-16 00:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ['-date_depense'], 'verbose_name': 'Dépense', 'verbose_name_plural': 'Dépenses'},
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.CharField(choices=[('transport', 'Transport'), ('nourriture', 'Nourriture'), ('achat_materiel', 'Achat de matériel'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('autre', 'Autre')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='depense',
            name='date_depense',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
