# Generated by Django 5.2.1 on 2025-07-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotproduitpharmacie',
            name='pharmacie',
        ),
    ]
