# Generated by Django 5.2.1 on 2025-06-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitfabricant',
            name='prix_achat',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
