# Generated by Django 5.2.1 on 2025-06-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitfabricant',
            name='nombre_plaquettes_par_boite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
