# Generated by Django 5.2.1 on 2025-07-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_alter_produitfabricant_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricant',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='produitfabricant',
            name='nom',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
