# Generated by Django 5.2.1 on 2025-07-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0002_remove_lotproduitpharmacie_pharmacie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='pharmacie',
        ),
    ]
