# Generated by Django 5.2.1 on 2025-06-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('pharmacie', '0003_requisitionproduit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_personnalise', models.CharField(blank=True, max_length=100)),
                ('nombre_demandes', models.PositiveIntegerField(default=1)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptes.pharmacie')),
                ('produit_fabricant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.produitfabricant')),
            ],
        ),
        migrations.DeleteModel(
            name='RequisitionProduit',
        ),
    ]
