# Generated by Django 5.2.1 on 2025-06-09 16:14

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_rendezvous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='remarque',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='heure',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('à venir', 'à venir'), ('passé', 'passé')], default='à venir', max_length=10),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.client'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
