# Generated by Django 5.2.1 on 2025-06-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0007_lotproduitpharmacie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicitePharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publicites/')),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
