# Generated by Django 5.2.1 on 2025-06-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0008_publicitepharmacie'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotPharmaceutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_depot', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('quartier', models.CharField(max_length=255)),
                ('adresse_complete', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fabricant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='pharmacie.fabricant')),
            ],
        ),
    ]
