# Generated by Django 5.2.1 on 2025-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0009_depotpharmaceutique'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotpharmaceutique',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
