# Generated by Django 5.2.1 on 2025-06-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0010_depotpharmaceutique_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotpharmaceutique',
            name='ville',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
