# Generated by Django 5.2.1 on 2025-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Pharmacie active ?'),
        ),
    ]
