# Generated by Django 5.2.1 on 2025-06-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='date_activation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'activation"),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='duree_en_jours',
            field=models.PositiveIntegerField(default=30, verbose_name='Durée de validité (en jours)'),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='montant_mensuel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
