# Generated by Django 5.2.1 on 2025-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_pharmacie_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacie',
            options={},
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='montant_mensuel',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant mensuel à payer'),
        ),
    ]
