# Generated by Django 5.2.1 on 2025-07-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_remove_pharmacie_date_activation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
